<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.3 (Python 3.9.13 on win32)" generated="20230629 09:23:00.638" rpa="false" schemaversion="2">
<suite id="s1" name="Test" source="D:\SCM\robot_framework_proj\app_automate_test\Robots\poc\test.robot">
<test id="s1-t1" name="log Test">
<kw name="Log To Console" library="BuiltIn">
<arg>${WORD}</arg>
<doc>Logs the given message to the console.</doc>
<status status="PASS" starttime="20230629 09:23:00.910" endtime="20230629 09:23:00.911"/>
</kw>
<kw name="Log To Console" library="BuiltIn">
<arg>${CONFIG_ENV_LIST['SIT']}</arg>
<doc>Logs the given message to the console.</doc>
<status status="PASS" starttime="20230629 09:23:00.911" endtime="20230629 09:23:00.913"/>
</kw>
<status status="PASS" starttime="20230629 09:23:00.909" endtime="20230629 09:23:00.914"/>
</test>
<status status="PASS" starttime="20230629 09:23:00.640" endtime="20230629 09:23:00.917"/>
</suite>
<statistics>
<total>
<stat pass="1" fail="0" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="1" fail="0" skip="0" id="s1" name="Test">Test</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230629 09:23:00.903" level="ERROR">Error in file 'D:\SCM\robot_framework_proj\app_automate_test\resources\init.resource' on line 3: Resource file '..\keyword\init.resoure' does not exist.</msg>
<msg timestamp="20230629 09:23:00.906" level="ERROR">Error in file 'D:\SCM\robot_framework_proj\app_automate_test\resources\init.resource' on line 4: Resource file '..\locator\init.resoure' does not exist.</msg>
</errors>
</robot>
